#:import GoHomeButton local_console.gui.view.common.components.GoHomeButton

<AIModelScreenView>
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"
        padding: "10dp"
        spacing: "10dp"
        MDBoxLayout:
        # Top bar
            orientation: "horizontal"
            size_hint_y: 0.1

            MDBoxLayout:
            # Controls half
                orientation: "horizontal"
                padding: "15dp"
                size_hint_x: 0.3
                padding: "10dp"

                GoHomeButton:

                MDWidget:

            MDWidget:
                size_hint_x: 0.4

            MDBoxLayout:
                size_hint_x: 0.3
                spacing: "5dp"

                EntryLabel:
                    text: "Device:"
                    size_hint_x: 0.3
                    bold: True

                MDLabel:
                    text: app.selected
                    shorten: True
                    max_lines: 1
                    size_hint_x: 0.7
                    padding: "20dp", "5dp"
                    halign:"left"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.1
                            rounded_rectangle: self.x, self.y+15, self.width, self.height/2, 5, 5, 5, 5

        MDBoxLayout:
        # Model setup controls
            orientation: "horizontal"
            size_hint_y: 0.1

            MDBoxLayout:
                orientation: "horizontal"
                spacing: "10dp"
                padding: "10dp"

                PathSelectorCombo:
                    id: model_pick
                    name: 'Model location:'
                    icon: "file-cog"
                    selector: "file"
                    path: app.mdl.ai_model_file
                    on_selected: app.mdl.ai_model_file = args[1]

                MDButton:
                    id: btn_ota_file
                    on_release: if not self.disabled: root.controller.deploy()
                    pos_hint: {"center_y": 0.5}
                    disabled: not (app.mdl.is_ready and app.mdl.ai_model_file_valid and root.update_status_finished)
                    MDButtonText:
                        text: "Deploy"

        MDLabel:
            text: "Neural Model Update Status"
            halign: "center"
            font_style: 'Title'
            adaptive_height: True
            padding: 0, "10dp"

        MDBoxLayout:
        # Readout block
            orientation: "horizontal"
            size_hint_y: 0.8
            spacing: "10dp"
            padding: "20dp"

            CodeInputCustom:
                id: txt_ota_data
                size_hint_x: 0.7

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: 0.25

                MDLabel:
                    id: lbl_ota_status
                    text: "N/A"
                    font_style: 'Body'
                    halign: 'center'

                MDWidget:
