#:import JsonLexer pygments.lexers.JsonLexer
#:import CodeInputCustom local_console.gui.view.common.components.CodeInputCustom
#:import GoHomeButton local_console.gui.view.common.components.GoHomeButton
#:import ImageWithROI local_console.gui.view.common.components.ImageWithROI

<InferenceScreenView>
    md_bg_color: self.theme_cls.backgroundColor
    inference_data: self.inference_data

    MDBoxLayout:
        orientation: "vertical"

        MDBoxLayout:
        # Top bar
            orientation: "horizontal"
            size_hint_y: 0.1
            padding: "5dp"
            spacing: "5dp"

            MDBoxLayout:
            # Controls half
                orientation: "horizontal"
                size_hint_x: 0.4
                padding: "10dp"
                spacing: "10dp"

                GoHomeButton:

                MDButton:
                    id: btn_stream_control
                    on_release: root.controller.toggle_stream_status()
                    style: "elevated"
                    pos_hint: {"center_y": 0.5}
                    MDButtonText:
                        text: ("Stop" if app.mdl.is_streaming else "Start") + " Streaming"

                MDWidget:


            MDBoxLayout:
            # Status readout half
                orientation: "horizontal"
                size_hint_x: 0.3
                padding: "5dp"
                spacing: "5dp"

                MDIcon:
                    icon: "video-outline"
                    pos_hint: {'center_y': .5}

                MDLabel:
                    text: 'Streaming:'

                MDLabel:
                    id: stream_flag
                    text: "Disabled"
            MDBoxLayout:
                size_hint_x: 0.3
                spacing: "5dp"

                EntryLabel:
                    text: "Device:"
                    size_hint_x: 0.3
                    bold: True

                MDLabel:
                    text: app.selected
                    size_hint_x: 0.7
                    shorten: True
                    max_lines: 1
                    padding: "20dp", "5dp"
                    halign:"left"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.1
                            rounded_rectangle: self.x, self.y +15, self.width, self.height/2, 5, 5, 5, 5

        GridLayout:
        # File path
            md_bg_color: root.theme_cls.backgroundColor
            rows: 2
            cols: 2
            padding: "5dp"
            spacing: "5dp"
            size_hint_y: 0.1

            MDLabel:
                text: 'Image:'
                adaptive_width: True

            MDLabel:
                text: app.mdl.image_dir_path
                allow_selection: True
                allow_copy: True
                padding: "5sp"
                shorten: True
                shorten_from: "left"
                canvas.before:
                    Color:
                        rgb: 0, 0, 0
                    Line:
                        rounded_rectangle: self.x, self.y, self.width, self.height, 8
                        width: 1
            MDLabel:
                text: 'Inference:'
                adaptive_width: True

            MDLabel:
                text: app.mdl.inference_dir_path
                allow_selection: True
                allow_copy: True
                padding: "5sp"
                shorten: True
                shorten_from: "left"
                canvas.before:
                    Color:
                        rgb: 0, 0, 0
                    Line:
                        rounded_rectangle: self.x, self.y, self.width, self.height, 8
                        width: 1

        MDBoxLayout:
        # Image view half
            orientation: "horizontal"
            size_hint_y: 0.7
            padding: "5dp"
            spacing: "5dp"

            ImageWithROI:
                id: stream_image
                source: app.mdl.stream_image
                radius: "10dp"
                fit_mode: "contain"
                size_hint_x: 0.7

            MDBoxLayout:
                size_hint_x: 0.3
                orientation: "vertical"

                CodeInputCustom:
                    text: app.mdl.inference_field
