#:import JsonLexer pygments.lexers.JsonLexer
#:import roi_as_pixels local_console.core.camera.axis_mapping.pixel_roi_from_normals
#:import GoHomeButton local_console.gui.view.common.components.GoHomeButton
#:import ImageWithROI local_console.gui.view.common.components.ImageWithROI
#:import ROIState local_console.gui.view.common.components.ROIState

<StreamingScreenView>
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"


        MDBoxLayout:
        # Top bar

            orientation: "horizontal"
            size_hint_y: 0.1
            padding: "5dp"
            spacing: "5dp"

            MDBoxLayout:
            # Controls half
                orientation: "horizontal"
                size_hint_x: 0.3
                padding: "10dp"
                spacing: "10dp"

                GoHomeButton:

                MDWidget:
                    size_hint_x: 0.1

                MDButton:
                    id: btn_stream_control
                    on_release: if not self.disabled: root.controller.toggle_stream_status()
                    style: "elevated"
                    disabled: not root.can_stream
                    pos_hint: {"center_y": 0.5}
                    MDButtonText:
                        id: btn_stream_text
                        text: "Start Streaming"

                MDButton:
                    id: btn_roi_control
                    on_release: if not self.disabled: root.control_roi()
                    disabled: stream_image.state == ROIState.Disabled or not root.can_stream
                    style: "elevated"
                    pos_hint: {"center_y": 0.5}
                    MDButtonText:
                        text: "Set ROI"

                MDButton:
                    id: btn_roi_reset
                    on_release: if not self.disabled: root.reset_roi()
                    disabled: stream_image.state == ROIState.Disabled or not root.can_stream
                    style: "elevated"
                    pos_hint: {"center_y": 0.5}
                    MDButtonText:
                        text: "Reset ROI"

                MDWidget:

            MDWidget:
                size_hint_x: 0.4

            MDBoxLayout:
            # Status readout half
                spacing: "5dp"
                size_hint_x: 0.3

                EntryLabel:
                    text: "Device:"
                    size_hint_x: 0.3
                    bold: True

                MDLabel:
                    text: app.selected
                    size_hint_x: 0.7
                    shorten: True
                    max_lines: 1
                    padding: "20dp", "5dp"
                    halign:"left"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.1
                            rounded_rectangle: self.x, self.y +15, self.width, self.height/2, 5, 5, 5, 5

        MDBoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.05

            MDIcon:
                icon: "video-outline"
                pos_hint: {'center_y': .5}
                padding: "600dp", "0dp", "0dp", "0dp"
            MDLabel:
                text: 'Streaming:'
            MDLabel:
                id: stream_flag
                text: "Disabled"


        MDBoxLayout:
        # Image view half
            orientation: "horizontal"
            size_hint_y: 0.9
            padding: "5dp"
            spacing: "5dp"

            ImageWithROI:
                id: stream_image
                source: app.mdl.stream_image
                radius: "10dp"
                fit_mode: "contain"
                on_size: self.update_roi()
                on_texture: self.prime_for_roi(args[1])
                size_hint_x: 0.7

            MDBoxLayout:
                size_hint_x: 0.3
                orientation: "vertical"

                MDBoxLayout:
                    size_hint_y: 0.65

                MDGridLayout:
                    size_hint_y: 0.35
                    cols: 3
                    padding: "10sp"
                    spacing: "2sp"

                    MDLabel:
                        text: 'ROI'
                        font_style: "Title"
                    MDLabel:
                        text: 'Offset'
                        font_style: "Body"
                    MDLabel:
                        text: 'Size'
                        font_style: "Body"
                    MDLabel:
                        text: 'H:'
                        font_style: "Body"
                    MDLabel:
                        id: lbl_roi_h_offset
                        text: str(roi_as_pixels(app.mdl.roi)[0][0])
                    MDLabel:
                        id: lbl_roi_h_size
                        text: str(roi_as_pixels(app.mdl.roi)[1][0])
                    MDLabel:
                        text: 'V:'
                        font_style: "Body"
                    MDLabel:
                        id: lbl_roi_v_offset
                        text: str(roi_as_pixels(app.mdl.roi)[0][1])
                    MDLabel:
                        id: lbl_roi_v_size
                        text: str(roi_as_pixels(app.mdl.roi)[1][1])
