<FirmwareScreenView>
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"
        padding: "10dp"
        spacing: "10dp"
        MDBoxLayout:
        # Top bar
            orientation: "horizontal"
            size_hint_y: 0.1

            MDBoxLayout:
            # Controls half
                orientation: "horizontal"
                padding: "15dp"
                size_hint_x: 0.3
                padding: "10dp"

                GoHomeButton:

                MDWidget:

            MDWidget:
                size_hint_x: 0.4

            MDBoxLayout:
                size_hint_x: 0.3
                spacing: "5dp"

                EntryLabel:
                    text: "Device:"
                    size_hint_x: 0.3
                    bold: True

                MDLabel:
                    text: app.selected
                    shorten: True
                    max_lines: 1
                    size_hint_x: 0.7
                    padding: "20dp", "5dp"
                    halign:"left"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.1
                            rounded_rectangle: self.x, self.y+15, self.width, self.height/2, 5, 5, 5, 5

        MDBoxLayout:
        # Firmware update controls
            orientation: "vertical"
            size_hint_y: 0.2

            MDBoxLayout:
                orientation: "horizontal"
                spacing: "10dp"
                padding: "10dp"

                EntryLabel:
                    text: "Select Firmware Type:"
                    halign: "left"
                    adaptive_width: True

                FirmwareDropDownItem:
                    _selected_type: root.map_ota_type(app.mdl.firmware_file_type)
                    on_selected: app.mdl.firmware_file_type = root.fw_type_ota_map[args[1]]
                    padding: "10dp", "0dp"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.0
                            rounded_rectangle: self.x, self.y, self.width, self.height, 4

                MDWidget:
                    size_hint_x: 0.378

            MDBoxLayout:
                orientation: "horizontal"
                spacing: "10dp"
                padding: "10dp"

                PathSelectorCombo:
                    id: firmware_pick
                    name: "Select Firmware:"
                    icon: "file-cog"
                    selector: "file"
                    path: str(app.mdl.firmware_file)
                    on_selected: app.mdl.firmware_file = args[1]

                MDButton:
                    id: btn_update_firmware
                    on_release: if not self.disabled: root.controller.update_firmware()
                    pos_hint: {"center_y": 0.5}
                    disabled:  not (app.mdl.is_ready and app.mdl.firmware_file_valid and app.mdl.firmware_file_version and root.update_status_finished)
                    MDButtonText:
                        text: "Update"

        MDBoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.8

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: 0.5
                spacing: "10dp"
                padding: "10dp"

                MDLabel:
                    text: "Firmware Status"
                    bold: True
                    halign: "center"
                    adaptive_height: True

                CodeInputCustom:
                    id: txt_ota_data

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: 0.5
                spacing: "10dp"
                padding: "10dp"

                MDLabel:
                    text: "Input Firmware Information"
                    bold: True
                    halign: "center"
                    adaptive_height: True

                MDGridLayout:
                    cols: 2
                    spacing: "10dp", "10dp"
                    padding: "10dp", "20dp"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1
                            rectangle: self.x, self.y, self.width, self.height

                    EntryLabel:
                        text: "Version:"
                        size_hint_x: 0.4
                        size_hint_y: None
                        height: "50dp"
                    MDTextField:
                        id: txt_firmware_file_version
                        text: app.mdl.firmware_file_version
                        on_text: app.mdl.firmware_file_version = args[1]
                        size_hint_y: None
                        max_height: "50dp"
                        height: "50dp"

                        MDTextFieldHintText:
                            text: "Input firmware version"
                            text_color_normal: "lightgray"

                    EntryLabel:
                        text: "Hash Value:"
                        size_hint_x: 0.4
                        size_hint_y: None
                        height: "50dp"
                    MDTextField:
                        id: txt_firmware_file_hash
                        text: app.mdl.firmware_file_hash
                        size_hint_y: None
                        max_height: "50dp"
                        height: "50dp"
                        readonly: True
                        disabled: True

                MDLabel:
                    text: "Download Progress"
                    bold: True
                    halign: "center"
                    adaptive_height: True
                ProgressBar:
                    id: progress_downloading
                    # The following binding is not supported by Kivy.
                    # It is the reason for bind_widget_property().
                    #value: root.transients.progress_download
                    size_hint_y: None
                    height: "20dp"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1
                            rectangle: self.x, self.y, self.width, self.height

                MDLabel:
                    text: "Update Progress"
                    bold: True
                    halign: "center"
                    adaptive_height: True
                ProgressBar:
                    id: progress_updating
                    # The following binding is not supported by Kivy.
                    # It is the reason for bind_widget_property().
                    #value: root.transients.progress_update
                    size_hint_y: None
                    height: "20dp"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1
                            rectangle: self.x, self.y, self.width, self.height

                MDLabel:
                    text: "Update Status"
                    bold: True
                    halign: "center"
                    adaptive_height: True
                MDLabel:
                    id: lbl_ota_status
                    # The following binding is not supported by Kivy.
                    # It is the reason for bind_widget_property().
                    #text: root.transients.update_status
                    font_style: "Body"
                    halign: "center"
                    size_hint_y: 0.4
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1
                            rectangle: self.x, self.y, self.width, self.height
