#:import AppTypeCombo local_console.gui.view.common.components.AppTypeCombo
#:import FileSizeCombo local_console.gui.view.common.components.FileSizeCombo
#:import GoHomeButton local_console.gui.view.common.components.GoHomeButton
#:import PathSelectorCombo local_console.gui.view.common.components.PathSelectorCombo
#:import Path pathlib.Path

<ConfigurationScreenView>
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"
        padding: "10dp"
        spacing: "10dp"
        MDBoxLayout:
        # Top bar
            orientation: "horizontal"
            size_hint_y: 0.1

            MDBoxLayout:
            # Controls half
                orientation: "horizontal"
                padding: "15dp"
                size_hint_x: 0.3
                padding: "10dp"

                GoHomeButton:

                MDWidget:

            MDWidget:
                size_hint_x: 0.4

            MDBoxLayout:
                size_hint_x: 0.3
                spacing: "5dp"

                EntryLabel:
                    text: "Device:"
                    size_hint_x: 0.3
                    bold: True

                MDLabel:
                    text: app.selected
                    shorten: True
                    max_lines: 1
                    size_hint_x: 0.7
                    padding: "20dp", "5dp"
                    halign:"left"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.1
                            rounded_rectangle: self.x, self.y+15, self.width, self.height/2, 5, 5, 5, 5

        MDBoxLayout:
        # Configuration controls
            orientation: "vertical"
            size_hint_y: 0.9
            padding: "15dp"
            spacing: "15dp"
            spacing_y: "5dp"

            PathSelectorCombo:
            # Image dir
                id: image_dir_pick
                name: 'Image dir:'
                icon: "folder-cog"
                path: app.mdl.image_dir_path
                search: "dirs"
                on_selected: root.controller.update_image_directory(args[1])

            PathSelectorCombo:
            # Inference dir
                id: inference_dir_pick
                name: 'Inference dir:'
                icon: "folder-cog"
                path: app.mdl.inference_dir_path
                search: "dirs"
                on_selected: root.controller.update_inferences_directory(args[1])

            FileSizeCombo:
                id: lbl_file_selector
                _spec: app.mdl.size
                _selected_unit: app.mdl.unit
                label: "Max total size from image and inference folders:"
                on_value: root.controller.update_total_max_size(args[1])

            MDLabel:
                text: "[b]Application configuration[/b]"
                markup: True

            AppTypeCombo:
                label: "Type:"
                _selected_unit: app.mdl.vapp_type
                on_selected: app.mdl.vapp_type = args[1]

            PathSelectorCombo:
                id: schema_pick
                name: 'Schema:'
                icon: "folder-cog"
                selector: "file"
                ext: [".fbs"]
                path: str(app.mdl.vapp_schema_file)
                on_selected: app.mdl.vapp_schema_file = self.accept_path(args[1])

            PathSelectorCombo:
                id: app_configuration_pick
                name: 'Configuration:'
                icon: "folder-cog"
                selector: "file"
                ext: [".json"]
                path: str(app.mdl.vapp_config_file)
                on_selected: app.mdl.vapp_config_file = self.accept_path(args[1])

            PathSelectorCombo:
                id: labels_pick
                name: 'Labels:'
                icon: "folder-cog"
                selector: "file"
                ext: [".txt"]
                path: str(app.mdl.vapp_labels_file)
                on_selected: app.mdl.vapp_labels_file = self.accept_path(args[1])
                disabled: True

            MDBoxLayout:

            MDBoxLayout:
                orientation: "horizontal"

                MDBoxLayout:

                MDExtendedFabButton:
                    id: btn_process_schema
                    on_release: root.controller.apply_configuration()
                    pos_hint: {"center_y": 0.5}
                    size_hint_x: 0.5

                    MDExtendedFabButtonText:
                        text: "Apply Configuration"
                        adaptive_height: False

                MDBoxLayout:

        MDBoxLayout:
        # Padding
            orientation: "horizontal"
            size_hint_y: 0.05
