#:import CodeInputCustom local_console.gui.view.common.components.CodeInputCustom
#:import GoHomeButton local_console.gui.view.common.components.GoHomeButton
#:import PathSelectorCombo local_console.gui.view.common.components.PathSelectorCombo

<ApplicationsScreenView>
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"
        padding: "10dp"
        spacing: "10dp"
        MDBoxLayout:
        # Top bar
            orientation: "horizontal"
            size_hint_y: 0.1

            MDBoxLayout:
            # Controls half
                orientation: "horizontal"
                padding: "15dp"
                size_hint_x: 0.3
                padding: "10dp"

                GoHomeButton:

                MDWidget:

            MDWidget:
                size_hint_x: 0.4

            MDBoxLayout:
                size_hint_x: 0.3
                spacing: "5dp"

                EntryLabel:
                    text: "Device:"
                    size_hint_x: 0.3
                    bold: True

                MDLabel:
                    text: app.selected
                    shorten: True
                    max_lines: 1
                    size_hint_x: 0.7
                    padding: "20dp", "5dp"
                    halign:"left"
                    canvas.before:
                        Color:
                            rgba: 0, 0, 0, 1
                        Line:
                            width: 1.1
                            rounded_rectangle: self.x, self.y+15, self.width, self.height/2, 5, 5, 5, 5

        MDBoxLayout:
        # Top bar
            orientation: "horizontal"
            size_hint_y: 0.1

            MDBoxLayout:
                orientation: "horizontal"
                spacing: "10dp"
                padding: "10dp"

                PathSelectorCombo:
                    id: app_file
                    name: 'App location:'
                    icon: "file-cog"
                    selector: "file"
                    path: app.mdl.module_file
                    on_selected: root.select_path(args[1])

                MDButton:
                    id: btn_deploy_file
                    on_release: if not self.disabled: root.controller.deploy()
                    pos_hint: {"center_y": 0.5}
                    disabled: not (app.mdl.is_ready and root.app_file_valid)
                    MDButtonText:
                        text: "Deploy"

        MDBoxLayout:
        # Title
            orientation: "horizontal"
            size_hint_y: 0.1

            MDWidget:

            MDLabel:
                text: "Deployment Status"
                font_style: 'Title'
                adaptive_height: True

            MDWidget:

        MDBoxLayout:
        # Readout block
            orientation: "horizontal"
            size_hint_y: 0.8
            spacing: "10dp"
            padding: "20dp"

            CodeInputCustom:
                id: txt_deployment_data
                text: app.mdl.deploy_status
                size_hint_x: 0.7

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: 0.25

                MDLabel:
                    text: "Current stage:"
                    font_style: 'Body'
                    adaptive_width: True
                    size_hint_y: 0.1

                MDGridLayout:
                    id: layout_status
                    rows: 1
                    size_hint_y: 0.2

                    # Start this way by default
                    MDLabel:
                        text: "N/A"

                MDWidget:
                    size_hint_y: 0.7
