#!/usr/bin/env python
# Copyright 2024 Sony Semiconductor Solutions Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
"""
This script converts the SBOM file generated by cyclonedx-py into csv format.
"""
import sys

from utils import get_license_token
from utils import read_licenses_csv
from utils import WHITELIST_PATH


def get_unique_licenses(file_path: str) -> list[str]:
    list_raw_licenses: list[str] = read_licenses_csv(file_path)
    set_unique_key_licenses: set[str] = {
        license_key
        for license_raw in list_raw_licenses
        for license_key in get_license_token(license_raw)
    }

    return sorted(list(set_unique_key_licenses))


if __name__ == "__main__":
    licenses_path: str = sys.argv[1]
    list_unique_licenses: list[str] = get_unique_licenses(licenses_path)
    with open(WHITELIST_PATH, "w") as f:
        for license in list_unique_licenses:
            f.write(license + "\n")
